# POST http://10.0.4.20:5055/api/auth/login HTTP/1.1
# content-type: application/json

# {
#     "username": "admin",
#     "password": "1234"
# }

POST http://10.0.4.20:5055/api/product/all HTTP/1.1
# GET http://10.0.4.20:5055/api/guest/fake HTTP/1.1

# GET http://10.0.4.20:5055/api/auth/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlR1YW5JVCIsImlkIjoiMjk1Mzc5MDctNENGNS1FRTExLUExRDQtMDREOUY1QzlEMkVCIiwicm9sZSI6eyJST0xFX0lEIjoiNUZFMjBDRUMtNjJCQi1FRTExLUExQ0ItQjVCNDE2NjM5RUM1IiwiUk9MRV9OQU1FIjoiQURNSU4ifSwiZW1haWwiOm51bGwsImlhdCI6MTcxMjc5NzY5NCwiZXhwIjoxNzEyODg0MDk0fQ.3Sl0bcWFpn-oUZxa5kj0agIroMI0uI5VrRGwMhKFshU